# @format
name: Generate Open Graph Images

on:
    push:
        branches: [main]

jobs:
    generate_ogimages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: npm install
              run: npm ci
            - name: generate images
              run: node index.js
            - name: push to another branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: assets
                  MESSAGE: 'Generate Open Graph Images 🤖'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
