# @format
name: Generate Open Graph Images

on:
    push:
        branches: [main]

jobs:
    generate_ogimages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: npm install
              run: npm ci
            - name: generate images
              run: node index.js
            - name: push to GitHub
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add assets/opengraph
                  git commit -m "Generate Open Graph Images 🤖"
                  git push
