# @format

name: Generate Open Graph Images

on:
    push:
        branches: [main]

jobs:
    generate_files:
        runs-on: ubuntu-latest
        container: lironavon/docker-puppeteer-container:14.16.0
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: node_modules-${{ hashFiles('**/package-lock.json')}}
            - run: |
                  npm ci --ignore-scripts
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  node index.js
                  git add assets/opengraph
                  git commit -m "Generate Open Graph Images 🤖"
                  git push
